# Generated by Django 5.1.4 on 2024-12-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('cod_coordenacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_coordenacao', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'coordenacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('cod_diretoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_diretoria', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'diretoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cod_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(blank=True, max_length=50, null=True)),
                ('informacoes_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('ementa', models.CharField(blank=True, max_length=800, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=255, null=True)),
                ('conteudo_programatico', models.CharField(blank=True, max_length=1200, null=True)),
                ('metodologia', models.CharField(blank=True, max_length=1200, null=True)),
                ('recursos_utilizados', models.CharField(blank=True, max_length=500, null=True)),
                ('sistematica_avaliacao', models.CharField(blank=True, max_length=255, null=True)),
                ('referencias', models.CharField(blank=True, max_length=300, null=True)),
                ('cod_coordenacao', models.ForeignKey(db_column='cod_coordenacao', default='SEM COORDENAÇÃO', on_delete=django.db.models.deletion.SET_DEFAULT, to='cursos.coordenacao')),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='coordenacao',
            name='cod_diretoria',
            field=models.ForeignKey(db_column='cod_diretoria', on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.diretoria'),
        ),
    ]
