# Generated by Django 5.1.4 on 2024-12-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cod_coordenacao',
            field=models.ForeignKey(db_column='cod_coordenacao', on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.coordenacao'),
        ),
    ]
