# Generated by Django 5.1.4 on 2024-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_cod_coordenacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='conteudo_programatico',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ementa',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='informacoes_curso',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='metodologia',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='objetivo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='recursos_utilizados',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='referencias',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sistematica_avaliacao',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
