# Generated by Django 5.1.4 on 2024-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_slug_alter_curso_conteudo_programatico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
